C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\pydantic\_internal\_config.py:341: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
  warnings.warn(message, UserWarning)
03:35:37 [INFO] [App.UI.CacheUtils] Utilitaires de cache UI définis.
03:35:37 [INFO] [App.UI.FetchUtils] Utilitaires de fetch UI définis.
03:35:37 [INFO] [App.UI.VerificationUtils] Utilitaires de vérification UI définis.
03:35:37 [INFO] [App.UI.Utils] Module principal des utilitaires UI (utils.py) initialisé et sous-modules importés.
03:35:37 [INFO] [Services.CacheService] Répertoire de cache initialisé: c:\dev\2025-Epita-Intelligence-Symbolique\_temp\text_cache
03:35:37 [INFO] [Services.FetchService] FetchService initialisé avec Tika URL: https://tika.open-webui.myia.io/tika, timeout: 30s
03:35:37 [WARNING] [Services.CryptoService] Service de chiffrement initialisé sans clé. Le chiffrement est désactivé.
03:35:37 [INFO] [InformalDefinitions] Classe InformalAnalysisPlugin (V12 avec nouvelles fonctions) définie.
03:35:37 [INFO] [InformalDefinitions] Instructions Système INFORMAL_AGENT_INSTRUCTIONS (V15 avec nouvelles fonctions) définies.
03:35:39 [INFO] [argumentation_analysis.core.bootstrap] Project root (from bootstrap.py) added to sys.path: C:\dev\2025-Epita-Intelligence-Symbolique
INFO:     Started server process [24136]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:5004 (Press CTRL+C to quit)
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 714, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 734, in app
    await route.handle(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\jsboi\.conda\envs\projet-is\lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
  File "c:\dev\2025-Epita-Intelligence-Symbolique\api\endpoints.py", line 61, in status_endpoint
    service_available = await analysis_service.is_available() # Supposing this method exists
TypeError: object bool can't be used in 'await' expression
